### ISSUE TITLE
Uncaught TypeError: router.afterEach is not a function

### ISSUE THREAD

**Issue by keithmifsud** [skyronic/vue-spa#2]
Hi,

I have this error and not sure how to solve it. I doubled checked that I'm using the same versions of each package as in this repo.

Uncaught TypeError: router.afterEach is not a function

**Comment by coedycode** [comment]
I had the same problem, syncing my instance of the router instead of the imported router module fixed it for me.

`import Vue from 'vue'
import { sync } from 'vuex-router-sync'
import VueRouter from 'vue-router'
import store from './vuex/store'

Vue.use(VueRouter)

let router = new VueRouter({
  root: '/',
  history: false
})

sync(store, router)`

**Comment by keithmifsud** [comment]
Thanks @coedycode ... I'll give it a try on the next new project.

**Comment by skyronic** [comment]
hey the versions are updated and i checked the router now. should be working. Thanks!
